# Generated by Django 3.2.6 on 2021-08-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0002_appiled_for_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appiled_for',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='appiled_for',
            name='uploaded',
        ),
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='static/uploads')),
                ('contest_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contest_app.contests')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_app.users_data')),
            ],
        ),
    ]
