# Generated by Django 3.2.6 on 2021-08-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0003_auto_20210810_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='sloka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_text', models.CharField(max_length=1000)),
                ('hin_text', models.CharField(max_length=1000)),
                ('audio', models.FileField(upload_to='static/sloka_audios')),
            ],
        ),
    ]
