# Generated by Django 3.2.6 on 2021-08-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0004_sloka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sloka',
            name='eng_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sloka',
            name='hin_text',
            field=models.TextField(max_length=1000),
        ),
    ]
