# Generated by Django 3.2.6 on 2021-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0005_auto_20210810_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sloka',
            name='audio',
            field=models.CharField(max_length=1000),
        ),
    ]
