# Generated by Django 3.2.6 on 2021-08-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0006_alter_sloka_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_data',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='users_data',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='users_data',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
