# Generated by Django 3.2.6 on 2021-08-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0008_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sloka',
            old_name='audio',
            new_name='eng_audio',
        ),
        migrations.AddField(
            model_name='sloka',
            name='hin_audio',
            field=models.CharField(default='Hari', max_length=1000),
            preserve_default=False,
        ),
    ]
