# Generated by Django 3.2.6 on 2021-08-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0011_auto_20210818_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question',
            name='answer',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
