# Generated by Django 3.2.6 on 2021-08-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0012_alter_quiz_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appiled_for',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='option1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='option2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='option3',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='option4',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
