# Generated by Django 3.2.6 on 2021-08-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0013_auto_20210825_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='coordinator_name',
            field=models.CharField(default='dsada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contests',
            name='coordinator_phone',
            field=models.IntegerField(default='2312', max_length=100),
            preserve_default=False,
        ),
    ]
