# Generated by Django 3.2.6 on 2021-08-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0014_auto_20210825_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='coordinator_phone',
            field=models.IntegerField(),
        ),
    ]
