# Generated by Django 3.2.4 on 2021-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0015_alter_contests_coordinator_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_an',
            name='correct_answer',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
